name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/reusable.yml
    with:
      who-to-greet: '@binaryluke'

  use-output:
    needs: [call-workflow]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
